### ISSUE TITLE
Do you want to apply a CS ruleset in this repo?

### ISSUE THREAD

**Issue by LordSimal** [rrd108/cakephp-cors#3]
Usually CakePHP plugins comply to the CS ruleset of https://github.com/cakephp/cakephp-codesniffer which is the same as a normal CakePHP app.

This can then of course be checked inside Github CI as well so that any incoming PR will comply to this as well.

**Comment by rrd108** [comment]
yes, it would be good.

Will you add this to the workflow?

**Comment by LordSimal** [comment]
Then I will prepare this for you, yes
